import { DIFFICULTY, TChampion } from './types';

export const champions: TChampion[] = [
    {
        id: 1,
        name: 'Morgana',
        img: 'morgana.jpg',
        attack: 2,
        defense: 6,
        magic: 8,
        difficulty: DIFFICULTY.EASY,
    },
    {
        id: 2,
        name: 'Leona',
        img: 'leona.jpg',
        attack: 4,
        defense: 8,
        magic: 3,
        difficulty: DIFFICULTY.MEDIUM,
    },
    {
        id: 3,
        name: 'Nami',
        img: 'nami.jpg',
        attack: 4,
        defense: 3,
        magic: 7,
        difficulty: DIFFICULTY.MEDIUM,
    },
    {
        id: 4,
        name: 'Braum',
        img: 'braum.jpg',
        attack: 3,
        defense: 9,
        magic: 4,
        difficulty: DIFFICULTY.EASY,
    },
    {
        id: 5,
        name: 'Lulu',
        img: 'lulu.jpg',
        attack: 4,
        defense: 5,
        magic: 7,
        difficulty: DIFFICULTY.MEDIUM,
    },
    {
        id: 6,
        name: 'Rakan',
        img: 'rakan.jpg',
        attack: 2,
        defense: 4,
        magic: 8,
        difficulty: DIFFICULTY.MEDIUM,
    },
    {
        id: 7,
        name: 'Yuumi',
        img: 'yuumi.jpg',
        attack: 1,
        defense: 2,
        magic: 9,
        difficulty: DIFFICULTY.EASY,
    },
    {
        id: 8,
        name: 'Alistar',
        img: 'alistar.jpg',
        attack: 3,
        defense: 9,
        magic: 5,
        difficulty: DIFFICULTY.HARD,
    },
    {
        id: 9,
        name: 'Zyra',
        img: 'zyra.jpg',
        attack: 4,
        defense: 3,
        magic: 8,
        difficulty: DIFFICULTY.HARD,
    },
    {
        id: 10,
        name: 'Nautilus',
        img: 'nautilus.jpg',
        attack: 4,
        defense: 6,
        magic: 6,
        difficulty: DIFFICULTY.MEDIUM,
    },
];
